version: '2'

services:
    jekyll:
        build: docker/jekyll
        container_name: alcalyn_jekyll
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        ports:
            - 4000:4000
        command: bash -c "bundle install && bundle exec jekyll serve --host=0.0.0.0"
